### example api call to upload JSON blueprint to xOpera REST API
### change localhost to xOpera REST_API's IP


# curl -H "Content-Type: application/json" -X "POST" --data-binary @blueprints-json/ATOS_openstack_testbed/atos-nginx-test-blueprint.json localhost:5000/manage
POST localhost:5000/manage
Content-Type: application/json

< blueprints-json/ATOS_openstack_testbed/atos-nginx-test-blueprint.json

###
