tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - modules/hpc/collection/main_hpc.yml


topology_template:

  inputs:
    frontend-address:
      type: string
    user:
      type: string
    key-location:
      type: string
    email:
      type: string


  node_templates:

  #HPC
    hpc-wm:
      type: sodalite.nodes.hpc.wm
      attributes:
        public_address: { get_input: frontend-address }
        username: { get_input: user }
        ssh-key: { get_input: key-location }

    hpc-job:
      type: sodalite.nodes.hpc.job
      properties:
        name: hpc-test-1
        script: |
                  #!/bin/sh

                  sleep 30
                  echo "test"
        workspace: ~
        ppn: 1
        walltime: 00:10:00
        email: { get_input: email }
        enable_audit: true
      requirements:
        - host: hpc-wm

#Result
    hpc-job-result:
      type: sodalite.nodes.hpc.job.result
      requirements:
        - host: hpc-wm
        - job: hpc-job
